"""Nightly paper-trading evaluation: generate signals, then act on them.

The loop runs once per night, after the close:

    1. Fetch a year of daily bars for every symbol the account watches.
    2. Replay the bound strategy over those bars *through the same engine the
       backtest used*, so the signal is generated by identical code.
    3. Record every signal, including the ones that are not acted on.
    4. Execute the actionable ones against the latest close.

Step 2 is the reason this module reuses `app.engine` rather than
reimplementing the entry rules. A live runner that reimplements the strategy
diverges from the backtest silently, and then the divergence report measures
two different strategies instead of one strategy in two environments.

Fills are at the latest close. In a real account the order would go in at the
next open, which the engine already models — but a nightly job has no next
open to wait for, so the close is used and the approximation is stated rather
than hidden.
"""

import logging
from datetime import date
from typing import Any, Dict, List, Optional, Sequence

import pandas as pd

from app import symbols as symbol_master
from app.db import session_scope
from app.db.models import PaperAccount
from app.engine.feed import DataFeed
from app.engine.runner import run
from app.engine.sizer import build_sizer
from app.engine.strategies import build_strategy
from app.paper import ledger
from app.yf_frames import close_series

logger = logging.getLogger(__name__)

HISTORY_PERIOD = "1y"


def latest_prices(symbols: Sequence[str]) -> Dict[str, float]:
    """Latest daily close per NSE symbol, in one batched download."""
    if not symbols:
        return {}
    try:
        import yfinance as yf
    except ImportError:
        logger.error("yfinance unavailable; paper positions cannot be marked to market")
        return {}

    tickers = {
        symbol: symbol_master.to_yfinance(symbol) or f"{symbol}.NS" for symbol in symbols
    }
    try:
        data = yf.download(
            list(tickers.values()), period="5d", interval="1d",
            progress=False, auto_adjust=False, group_by="ticker", threads=True,
        )
    except Exception as exc:
        logger.warning("Paper price fetch failed: %s", exc)
        return {}

    prices: Dict[str, float] = {}
    for symbol, ticker in tickers.items():
        closes = close_series(data, ticker)
        if closes is not None:
            prices[symbol] = float(closes.iloc[-1])
    return prices


def fetch_history(symbol: str, period: str = HISTORY_PERIOD) -> Optional[pd.DataFrame]:
    try:
        import yfinance as yf
    except ImportError:
        return None
    ticker = symbol_master.to_yfinance(symbol) or f"{symbol}.NS"
    try:
        frame = yf.Ticker(ticker).history(period=period, interval="1d")
    except Exception as exc:
        logger.warning("History fetch failed for %s: %s", symbol, exc)
        return None
    if frame is None or frame.empty:
        return None
    if frame.index.tz is not None:
        frame.index = frame.index.tz_localize(None)
    return frame


def evaluate_symbol(
    paper: PaperAccount, symbol: str, frame: pd.DataFrame
) -> Optional[Dict[str, Any]]:
    """Replay the strategy over history and report what it would do at the last bar.

    The engine is run over the whole window with a trivial capital base; what
    matters is not its P&L but whether its *final* order was a buy or a sell,
    because that is the decision the live account has to make tonight.
    """
    strategy_name = paper.strategy
    if not strategy_name:
        return None

    try:
        strategy = build_strategy(strategy_name, **(paper.strategy_params or {}))
        feed = DataFeed(symbol, frame)
        result = run(
            [feed], strategy,
            initial_capital=float(paper.initial_capital),
            sizer=build_sizer("percent", percent=0.95),
            start_index=strategy.warmup,
            close_at_end=False,  # an open position is a live "stay long", not an exit
        )
    except Exception as exc:
        logger.warning("Strategy replay failed for %s on %s: %s", strategy_name, symbol, exc)
        return None

    last_bar = len(feed) - 1
    # An order submitted on the final bar has no next bar to fill against, so
    # it is still sitting in the queue. That queue is exactly tonight's signal.
    pending = [
        order for order in result["orders"]
        if order["status"] == "PENDING" or (
            order["status"] == "EXPIRED" and "No bar available" in (order["reject_reason"] or "")
        )
    ]
    holds_position = bool(result["open_positions"])
    close = float(frame["Close"].iloc[-1])

    if pending:
        order = pending[-1]
        return {
            "symbol": symbol,
            "action": order["side"],
            "reason": order["reason"],
            "price": close,
            "quantity_hint": order["quantity"],
        }
    return {
        "symbol": symbol,
        "action": "HOLD" if holds_position else "NONE",
        "reason": "Strategy produced no order on the latest bar.",
        "price": close,
        "quantity_hint": 0,
    }


def run_account(paper_account_id: int, symbols: Sequence[str]) -> Dict[str, Any]:
    """Evaluate one paper account against a watchlist and execute its signals."""
    executed, recorded, skipped = 0, 0, 0
    details: List[Dict[str, Any]] = []

    with session_scope() as session:
        paper = session.get(PaperAccount, paper_account_id)
        if paper is None:
            raise KeyError(f"No paper account {paper_account_id}.")
        if not paper.active:
            return {"paper_account_id": paper_account_id, "skipped": "Account is inactive."}

        for symbol in symbols:
            frame = fetch_history(symbol)
            if frame is None or len(frame) < 60:
                skipped += 1
                details.append({"symbol": symbol, "outcome": "no usable price history"})
                continue

            signal = evaluate_symbol(paper, symbol, frame)
            if signal is None or signal["action"] == "NONE":
                skipped += 1
                continue

            position = ledger.position_for(session, paper, symbol)
            price = signal["price"]
            action = signal["action"]
            skip_reason: Optional[str] = None
            quantity = 0.0

            if action == "BUY":
                if float(position.quantity) > 0:
                    skip_reason = "Already holding this symbol."
                else:
                    quantity = int(float(paper.cash) * 0.95 // price)
                    if quantity <= 0:
                        skip_reason = "Not enough virtual cash for a single share."
            elif action == "SELL":
                quantity = float(position.quantity)
                if quantity <= 0:
                    skip_reason = "No position to sell."
            else:
                skip_reason = "Hold: no action required."

            record = ledger.record_signal(
                session, symbol=symbol, action=action,
                paper_account_id=paper.id, reference_price=price,
                executed=skip_reason is None,
                skip_reason=skip_reason,
                evidence={"reason": signal["reason"], "strategy": paper.strategy},
            )
            recorded += 1

            if skip_reason is not None:
                details.append({"symbol": symbol, "action": action, "skipped": skip_reason})
                continue

            try:
                order = ledger.execute(
                    session, paper, symbol, action, quantity, price,
                    reason=signal["reason"], signal_id=record.id,
                )
                executed += 1
                details.append(
                    {
                        "symbol": symbol,
                        "action": action,
                        "quantity": quantity,
                        "price": round(price, 2),
                        "order_id": order.id,
                    }
                )
            except (ledger.InsufficientFunds, ledger.NoPosition) as exc:
                record.executed = False
                record.skip_reason = str(exc)
                details.append({"symbol": symbol, "action": action, "skipped": str(exc)})

    return {
        "paper_account_id": paper_account_id,
        "symbols": len(symbols),
        "signals_recorded": recorded,
        "orders_executed": executed,
        "skipped": skipped,
        "details": details,
        "note": (
            "Paper fills use the latest daily close. A live order would fill at "
            "the next open, which the backtester models; the nightly job has no "
            "next open available."
        ),
    }


def mark_all_to_market() -> Dict[str, Any]:
    """Re-price every active paper account. Called by the nightly job."""
    from sqlalchemy import select

    marked, symbols_priced = 0, 0
    with session_scope() as session:
        accounts = list(
            session.scalars(select(PaperAccount).where(PaperAccount.active.is_(True)))
        )
        if not accounts:
            return {"job": "paper_mark_to_market", "accounts": 0, "marked": 0}

        from app.db.models import PaperPosition

        all_symbols = {
            position.symbol
            for position in session.scalars(
                select(PaperPosition).where(PaperPosition.quantity > 0)
            )
        }
        prices = latest_prices(sorted(all_symbols))
        symbols_priced = len(prices)

        for paper in accounts:
            ledger.valuation(session, paper, prices)
            marked += 1

    return {
        "job": "paper_mark_to_market",
        "accounts": len(accounts),
        "marked": marked,
        "symbols_priced": symbols_priced,
    }
